apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-ucylhmzd
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: tssc-quay-quay-tssc-quay.apps.cluster-fhj8w.fhj8w.sandbox2412.opentlc.com/tssc/go-ucylhmzd:5d6c23388661a9f0e052c52f571f099b2e617ee6@sha256:1230c62ea5dddca12a1115cec8d521744e3235c8a394a4fac52f75233af77758
        name: container-image  
